timestables/TimesTables/Timest4blesMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Timest4blesMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Practice()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

timestables/TimesTables/Timest4blesMVC/Controllers/PracticeController.cs
using System.Web.Mvc;

namespace Timest4blesMVC.Controllers
{
    public class PracticeController : Controller
    {
        // GET: Practice
        public ActionResult Index()
        {
            return View();
        }
    }
}

timestables/TimesTables/Timest4blesMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Learn your times tables</h1>
       <p class="btn btn-primary btn-lg" id="beginPracticing">@Html.ActionLink("Click me to begin", "Practice", "Home")</p>
</div>

<div class="row">
   
</div>

timestables/TimesTables/Timest4blesMVC/Views/Home/Practice.cshtml
@{
    ViewBag.Title = "Times Tables App";
}

    <section id="quiz">

        <fieldset id="choiceOfTables">
            <legend>Choose your tables</legend>
            <div role="toolbar" class="ui-controlgroup ui-controlgroup-horizontal ui-helper-clearfix">

                <label for="one" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">1</label>
                <input type="submit" name="one" id="one" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="two" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">2</label>
                <input type="submit" name="two" id="two" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="three" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">3</label>
                <input type="submit" name="three" id="three" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="four" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">4</label>
                <input type="submit" name="four" id="four" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="five" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">5</label>
                <input type="submit" name="five" id="five" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="six" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">6</label>
                <input type="submit" name="six" id="six" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="seven" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">7</label>
                <input type="submit" name="seven" id="seven" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="eight" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">8</label>
                <input type="submit" name="eight" id="eight" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="nine" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">9</label>
                <input type="submit" name="nine" id="nine" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="ten" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">10</label>
                <input type="submit" name="ten" id="ten" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="eleven" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">11</label>
                <input type="submit" name="eleven" id="eleven" class="ui-checkboxradio ui-helper-hidden-accessible" />
                <label for="twelve" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">12</label>
                <input type="submit" name="twelve" id="twelve" class="ui-checkboxradio ui-helper-hidden-accessible" />
            </div>
            <div id="selectAllDiv">
                <label id="selectAllLabel" for="selectAll" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item">All</label>
                <input type="submit" id="selectAll" name="selectAll" class="ui-checkboxradio ui-helper-hidden-accessible" />
            </div>
        </fieldset>

        <button type="button" id="startBtn" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item" onclick="startPracticing()">Start</button>

        <div id="question" style="display: none">
            <p id="firstNumber"></p>
            <p id="timesSign">X</p>
            <p id="secondNumber"></p>
            <p id="equalsSign">=</p>
            <input id="givenAnswer" type="text" class="ui-widget" />
            <input id="okBtn" type="button" value="OK" class="ui-button" />
            <input id="nextBtn" type="button" value="Next" class="ui-button" />
            <p id="errorMessage"></p>
        </div>
        <button type="button" id="endPractice" class="ui-button ui-widget ui-checkboxradio-checked ui-controlgroup-item" onclick="stopPracticing()">End Session</button>
    </section>

    <div id="ex1" style="display: none;">
        <p id="TotalAnswers"></p>
        <p id="MoreTime"></p>
        <p id="Revealed"></p>
        <a href="#" rel="modal:close">Close</a>
    </div>
    <!-- http://jquerymodal.com/ -->
    <p style="display: none"><a href="#ex1" rel="modal:open" id="openModalLink">Open Modal</a></p>

    <!-- save the form in a word doc to a file location on my comp, preselect the location used but let it be overridden -->
    <!-- email a copy of the form, to any email address -->
    <!-- output results in a funky graph -->

    <script src="~/Scripts/tt.js"></script>
    <script src="~/Scripts/Alerts.js"></script>

timestables/TimesTables/Timest4blesMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.1.0.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/tt.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/Content/sweetalert.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/jquery.modal.css" />
    <script src="~/Scripts/sweetalert.min.js"></script>
    <script src="~/Scripts/jquery.modal.js" type="text/javascript" charset="utf-8"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Practice", "Practice", "Home")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@ 
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>